name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    name: ${{matrix.lisp}} on ${{matrix.os}}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install Roswell
        shell: bash
        env:
          LISP: ${{matrix.lisp}}
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

      - name: Get Lisp info
        continue-on-error: true
        shell: bash
        run: |
          ros -e '(format t "Lisp: ~a ~a on ~a~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type)) -e '(setf *debugger-hook* (lambda (&rest ignorable) (declare (ignore ignorable)) (uiop:quit -1)))' -e '(ql:quickload "coalton-lsp/tests")' -e '(unless (fiasco:all-tests) (uiop:quit -1))'
